### ISSUE TITLE
500 error on `/api/admin/platforms/yeswehack/stats`

### ISSUE THREAD

**Issue by Serizao** [EasyRecon/Hunt3r#176]
I have got 500 error on the endpoint `/api/admin/platforms/yeswehack/stats` simple GET witout paramq

```

{"status":500,"error":"Internal Server Error","exception":"#\u003cTypeError: no implicit conversion of Symbol into Integer\u003e","traces":{"Application Trace":[{"exception_object_id":91800,"id":0,"trace":"app/models/platform_stat.rb:4:in `[]'"},{"exception_object_id":91800,"id":1,"trace":"app/models/platform_stat.rb:4:in `block in \u003cclass:PlatformStat\u003e'"},{"exception_object_id":91800,"id":12,"trace":"app/controllers/admin/platformstats_controller.rb:11:in `index'"}],"Framework Trace":[{"exception_object_id":91800,"id":2,"trace":"activerecord (7.0.2.4) lib/active_record/relation.rb:435:in `instance_exec'"},{"exception_object_id":91800,"id":3,"trace":"activerecord (7.0.2.4) lib/active_record/relation.rb:435:in `block in _exec_scope'"},{"exception_object_id":91800,"id":4,"trace":"activerecord (7.0.2.4) lib/active_record/relation.rb:880:in `_scoping'"},{"exception_object_id":91800,"id":5,"trace":"activerecord (7.0.2.4) lib/active_record/relation.rb:435:in `_exec_scope'"},{"exception_object_id":91800,"id":6,"trace":"activerecord (7.0.2.4) lib/active_record/scoping/named.rb:175:in `block in scope'"},{"exception_object_id":91800,"id":7,"trace":"activerecord (7.0.2.4) lib/active_record/relation/delegation.rb:67:in `block in filtered'"},{"exception_object_id":91800,"id":8,"trace":"activerecord (7.0.2.4) lib/active_record/relation.rb:880:in `_scoping'"},{"exception_object_id":91800,"id":9,"trace":"activerecord (7.0.2.4) lib/active_record/relation.rb:428:in `scoping'"},{"exception_object_id":91800,"id":10,"trace":"activerecord (7.0.2.4) lib/active_record/associations/collection_proxy.rb:1114:in `scoping'"},{"exception_object_id":91800,"id":11,"trace":"activerecord (7.0.2.4) lib/active_record/relation/delegation.rb:67:in `filtered'"},{"exception_object_id":91800,"id":13,"trace":"actionpack (7.0.2.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'"},{"exception_object_id":91800,"id":14,"trace":"actionpack (7.0.2.4) lib/abstract_controller/base.rb:214:in 
```

**Comment by JoshuaMart** [comment]
I can not reproduce, but we can test with https://github.com/EasyRecon/Hunt3r/pull/179

**Comment by Serizao** [comment]
Yes it seem to be solve :)
